### ISSUE TITLE
OpenRouteService

### ISSUE THREAD

**Issue by waschulte** [kkarsten62/QMapShack.AppImage#29]
A nice to have online router: openrouteservice.org.
Perhaps as replacement for MapQuest ?

**Comment by kkarsten62** [comment]
This repo "QMapShack.AppImage " is dedicated for building AppImages for QMS. Your ticket is related to a general enhancement around QMS, which will be handle in the official QMS Github repo: https://github.com/Maproom/qmapshack/issues. Please open a enhancement request in this repo. Please check for already existing ticket for such kind of request. Thanks.

**Comment by kkarsten62** [comment]
No more feedback ...
