### ISSUE TITLE
appimage 1.17.1 on Ubuntu 24.04: FATAL:credentials.cc(125)] Check failed: . : Permission denied (13)

### ISSUE THREAD

**Issue by barbudor** [kkarsten62/QMapShack.AppImage#30]
Hello
When starting `QMapShack-x86_64_Ubuntu-22.04.AppImage` 
I get the following error message:
```
--- QMapShack.AppImage starting

2024-01-14 12:12:44.062 [warning] "no file found for translations '/tmp/.mount_QMapSh9SS9vt/usr/share/qmapshack/translations/qmapshack_en' (using default)."
[3193:3193:0114/121244.263784:FATAL:credentials.cc(125)] Check failed: . : Permission denied (13)
/tmp/.mount_QMapSh9SS9vt/AppRun.wrapped: line 26:  3193 Trace/breakpoint trap   (core dumped) ${APPDIR}/usr/bin/qmapshack "$@"
``` 

If I mount the image using `QMapShack-x86_64_Ubuntu-22.04.AppImage --appimage-mount`
I can navigate to the translation folder and the english translation doesn't seem to be there
```
/tmp/.mount_QMapSh9RL1Xu/usr/share/qmapshack/translations$ ll
total 2628
-rw-r--r-- 1 root root 399651 Dec 20 13:37 qmapshack_ca.qm
-rw-r--r-- 1 root root 277117 Dec 20 13:37 qmapshack_cs.qm
-rw-r--r-- 1 root root 405955 Dec 20 13:37 qmapshack_de.qm
-rw-r--r-- 1 root root 386193 Dec 20 13:37 qmapshack_es.qm
-rw-r--r-- 1 root root 330529 Dec 20 13:37 qmapshack_fr.qm
-rw-r--r-- 1 root root 352003 Dec 20 13:37 qmapshack_it.qm
-rw-r--r-- 1 root root 135045 Dec 20 13:37 qmapshack_nl.qm
-rw-r--r-- 1 root root 406489 Dec 20 13:37 qmapshack_ru.qm
```

Could it be that the file is misisng from the AppImage ?

Thanks

**Comment by barbudor** [comment]
Actually the problem is not the 1st line that is only a warning but the 2 other lines
If I start for anohter language, hte warning disapear but the crash remains:
```
$ LANG=fr ./QMapShack-x86_64_Ubuntu-22.04.AppImage 

--- QMapShack.AppImage starting

[29876:29876:0120/121041.026958:FATAL:credentials.cc(125)] Check failed: . : Permission denied (13)
/tmp/.mount_QMapShxHm7GH/AppRun.wrapped: line 26: 29876 Trace/breakpoint trap   (core dumped) ${APPDIR}/usr/bin/qmapshack "$@"
```

**Comment by barbudor** [comment]
So my problem is related to my Ubuntu being the 24.04 development branch
The AppImage runs fines ona 23.10 VM

So I'm trying to build it for 24.04
Successfully built docker image `qms-appimage:0.0.0`  based on `ubuntu:24.04`. I had to do a few changes to my system and the Dockerfile:
- rebuild zlib and pigz to latest versions as the ones currently provided with 24.04 are not working. This is solved in zlib/pigz repo but the 24.04 repos are not updated
- change the base image to `ubuntu:24.04` 
- add mantic repos as noble one does include everything (libcurl4 was missing)

Now I'm running the docker to build QMapShack and the AppImage but if fails on running linuxdeploy:
```
/build_AppImage.sh: line 49: ./linuxdeploy-x86_64.AppImage: cannot execute: required file not found
```
Not much details on what could be the missing file ...

**Comment by kkarsten62** [comment]
I will start actions for a QMapShack.AppImage based on Ubuntu 24.04 when it is officially released in April. It's hard to say what is wrong here. Maybe you can try to build QMS in a "normal" Ubuntu 24.04 virtual machine first, to check if QMS is working for Ubuntu 24.04 at all.
Then make sure that the files `linuxdeploy-x86_64.AppImage` and `linuxdeploy-plugin-qt-x86_64.AppImage` exists in the root folder of the docker image.
Same for 
```
	&& cp -r /usr/share/gdal /AppDir/usr/share \
	&& cp -r /usr/share/proj /AppDir/usr/share \
	&& cp -r /usr/share/routino /AppDir/usr/share \
	&& cp /usr/bin/planetsplitter /AppDir/usr/bin \
	&& cp /usr/bin/gdalbuildvrt /AppDir/usr/bin \
   	&& cp -r /usr/share/qt5/translations /AppDir/usr
```
Translation file are always tricky. Some docker images differs here to a "normal" ISO image. Please check in a "normal" environment where the translation files are located and compare it to the structure in the docker image and `AppDir` folder. May be it is not necessary to copy it to the docker `AppDir` folder.

Then check if the `linuxdeploy` files are ready for Ubuntu 24.04.

In general: Building AppImages for new Linux OS are always tricky and fixing problems are mostly by try and error and finding the needle in the haystack.

HIH - Good luck.

**Comment by barbudor** [comment]
Hi
Actually the problem also occurs with"bare metal" package installed from APT
I will try to find  some time to open a discussion on Qmapshack repo to get some hints on how I can help on this
The earliest we can fix any problem related to Noble, the faster Qmapshack will run once it is available

**Comment by barbudor** [comment]
Update : Magic has happenned
I just installed a VM with Lubuntu 24.04 and both the "bare metal" Qmapshack 1.17.1 and the Appimage run as expected

Thanks
